# -*- coding: utf-8 -*-
"""
Created on Wed Dec  6 09:12:19 2017

@author: tobeannouncd

Pentagon numbers

Problem 44 

Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of 
D?
"""

import time

def is_pentag(n):
    i = (1 + (1 + 24 * n) ** 0.5) / 6
    return i == int(i)

def main():
    i = 2
    notFound = True
    while notFound:
        x = i * (3 * i - 1) // 2
        for j in range(i - 1, 0, -1):
            y = j * (3 * j - 1) // 2
            if is_pentag(x + y) and is_pentag(x - y):
                o = x - y
                notFound = False
                break
        i += 1
    print(o)
    

if __name__ == '__main__':
    t_beg = time.clock()
    main()
    t_end = time.clock()
    print('Executed in', (t_end - t_beg)*1000, 'ms')