# -*- coding: utf-8 -*-
"""
Created on Wed Dec  6 09:45:52 2017

@author: Tyler

Triangular, pentagonal, and hexagonal
Problem 45 
Triangle, pentagonal, and hexagonal numbers are generated by the following 
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def is_pentag(n):
    i = (1 + (1 + 24 * n) ** 0.5) / 6
    return i == int(i)

def main():
    notFound = True
    n = 143
    while notFound:
        n += 1
        h = n*(2*n - 1)
        if is_pentag(h):
            print(h)
            notFound = False

if __name__ == '__main__':
    import time
    t_beg = time.clock()
    main()
    t_end = time.clock()
    print('Executed in', t_end - t_beg, 'seconds')